[workspace]
channels = ["conda-forge"]
name = "image_blur_check"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
opencv = ">=4.12.0,<5"
numpy = ">=2.3.3,<3"
matplotlib = ">=3.10.6,<4"
